# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.2.0]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Ensure fresh node_modules and Install dependencies
        run: |
          rm -rf node_modules
          npm cache clean --force
          npm ci
        working-directory: ./test-react-leaflet-issue/

      - name: Debug Node Modules
        run: |
          echo "Listing contents of node_modules:"
          ls -F node_modules/react-router-dom/ 
          echo "Listing package-lock.json (first 20 lines):"
          head -n 20 package-lock.json
        working-directory: ./test-react-leaflet-issue/

      - name: Build project
        run: npm run build --if-present
        working-directory: ./test-react-leaflet-issue/

      - name: Run tests
        run: npm test
        working-directory: ./test-react-leaflet-issue/

