# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./code/awesome-project 

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.5"

    - name: Debug - List Backend Directory Contents (Before Install)
      run: ls -RF

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8 pytest
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: Debug - Verify Installed Packages & Python Path
      run: |
        echo "--- Python Version ---"
        python3 --version
        echo "--- pip List (Filtered for key packages) ---"
        pip3 list | grep -E 'fastapi|httpx|pytest|uvicorn|sqlalchemy'
        echo "--- Python sys.path ---"
        python3 -c "import sys; print(sys.path)"
        echo "--- Current Working Directory ---"
        pwd

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
